/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options for mock generation */
export interface MockOptions {
  /** Random seed for deterministic output */
  seed?: number
  /** Override specific values in the generated mock */
  overrides?: any
  /** Maximum depth for nested objects (default: 5) */
  maxDepth?: number
  /** Length of generated arrays (default: 2) */
  arrayLength?: number
  /** Whether to include optional properties (default: true) */
  includeOptional?: boolean
}
/** Test function to verify napi-rs setup */
export declare function hello(): string
/** Test function with parameters */
export declare function add(a: number, b: number): number
