/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options for mock generation */
export interface MockOptions {
  /** Random seed for deterministic output */
  seed?: number
  /** Override specific values in the generated mock */
  overrides?: any
  /** Maximum depth for nested objects (default: 5) */
  maxDepth?: number
  /** Length of generated arrays (default: 2) */
  arrayLength?: number
  /** Whether to include optional properties (default: true) */
  includeOptional?: boolean
}
/** Parse a .ts file and generate a mock for the given type. */
export declare function createMockFromFile(filePath: string, typeName: string, options?: MockOptions | undefined | null): any
/** Parse a .ts file and generate multiple mocks. */
export declare function createManyMocks(filePath: string, typeName: string, count: number, options?: MockOptions | undefined | null): Array<any>
/** List all type names in a .ts file. */
export declare function listTypes(filePath: string): Array<string>
/** Parse TypeScript source code and generate a mock (no file needed). */
export declare function mockFromSource(source: string, typeName: string, options?: MockOptions | undefined | null): any
/** Get the native module version. */
export declare function version(): string
