// @vitest-environment jsdom
/**
 * Integration test: uses a real schema generated by the CLI tool
 * to verify the full browser workflow end-to-end.
 */

import { describe, it, expect } from "vitest";
import {
  createMockFromSchema,
  createManyMocksFromSchema,
  listTypesFromSchema,
  createMockContext,
} from "../src/browser.js";
import schema from "../examples/types.schema.json";

describe("Browser integration (real CLI-generated schema)", () => {
  it("should list all types from the schema", () => {
    const types = listTypesFromSchema(schema);
    expect(types).toContain("User");
    expect(types).toContain("Product");
    expect(types).toContain("Order");
    expect(types).toContain("Address");
    expect(types).toContain("PaymentMethod");
    expect(types).toContain("UserRole");
    expect(types).toContain("OrderStatus");
    expect(types).toContain("ApiResponse");
  });

  it("should create a User mock", () => {
    const user = createMockFromSchema(schema, "User", { seed: 42 });
    expect(user).toBeDefined();
    const u = user as Record<string, unknown>;
    expect(typeof u.id).toBe("string");
    expect(typeof u.name).toBe("string");
    expect(typeof u.email).toBe("string");
    expect(typeof u.age).toBe("number");
    expect(["admin", "manager", "customer"]).toContain(u.role);
  });

  it("should create a Product mock", () => {
    const product = createMockFromSchema(schema, "Product", { seed: 42 });
    const p = product as Record<string, unknown>;
    expect(typeof p.id).toBe("string");
    expect(typeof p.title).toBe("string");
    expect(typeof p.price).toBe("number");
    expect(typeof p.inStock).toBe("boolean");
    expect(Array.isArray(p.tags)).toBe(true);
    expect(["electronics", "clothing", "books", "food"]).toContain(p.category);
  });

  it("should create an Order mock with nested objects", () => {
    const order = createMockFromSchema(schema, "Order", { seed: 42 });
    const o = order as Record<string, unknown>;
    expect(typeof o.id).toBe("string");
    expect(typeof o.user).toBe("object");
    expect(Array.isArray(o.items)).toBe(true);
    expect(["pending", "processing", "shipped", "delivered", "cancelled"]).toContain(o.status);
    // PaymentMethod enum
    expect(["CREDIT_CARD", "PAYPAL", "BANK_TRANSFER"]).toContain(o.paymentMethod);
    expect(typeof o.totalAmount).toBe("number");
  });

  it("should create an Address mock", () => {
    const address = createMockFromSchema(schema, "Address", { seed: 42 });
    const a = address as Record<string, unknown>;
    expect(typeof a.street).toBe("string");
    expect(typeof a.city).toBe("string");
    expect(typeof a.zipCode).toBe("string");
    expect(typeof a.country).toBe("string");
  });

  it("should create multiple mocks", () => {
    const users = createManyMocksFromSchema(schema, "User", 5, { seed: 42 });
    expect(users).toHaveLength(5);
  });

  it("should work with MockContext", () => {
    const ctx = createMockContext(schema, { seed: 42 });
    const user = ctx.mock("User");
    const order = ctx.mock("Order");
    const users = ctx.many("User", 3);

    expect(user).toBeDefined();
    expect(order).toBeDefined();
    expect(users).toHaveLength(3);
    expect(ctx.listTypes().length).toBeGreaterThan(0);
  });

  it("should support overrides", () => {
    const user = createMockFromSchema(schema, "User", {
      seed: 42,
      overrides: { name: "John Doe", email: "john@example.com", age: 25 },
    });
    const u = user as Record<string, unknown>;
    expect(u.name).toBe("John Doe");
    expect(u.email).toBe("john@example.com");
    expect(u.age).toBe(25);
  });

  it("should support nested overrides (merge)", () => {
    const order = createMockFromSchema(schema, "Order", {
      seed: 42,
      overrides: {
        id: "ORD-001",
        user: { name: "Alice" },
      },
    });
    const o = order as Record<string, unknown>;
    expect(o.id).toBe("ORD-001");
    const user = o.user as Record<string, unknown>;
    expect(user.name).toBe("Alice");
    // Other user fields should still be generated
    expect(typeof user.email).toBe("string");
  });

  it("should produce deterministic output with same seed", () => {
    const u1 = createMockFromSchema(schema, "User", { seed: 123 });
    const u2 = createMockFromSchema(schema, "User", { seed: 123 });
    expect(JSON.stringify(u1)).toBe(JSON.stringify(u2));
  });

  it("should produce different output with different seeds", () => {
    const u1 = createMockFromSchema(schema, "User", { seed: 1 });
    const u2 = createMockFromSchema(schema, "User", { seed: 2 });
    expect(JSON.stringify(u1)).not.toBe(JSON.stringify(u2));
  });

  it("should handle generic type (ApiResponse<User>)", () => {
    const response = createMockFromSchema(schema, "UserResponse", { seed: 42 });
    expect(response).toBeDefined();
    const r = response as Record<string, unknown>;
    // ApiResponse has: data, error, status, timestamp
    expect("data" in r || "error" in r || "status" in r || "timestamp" in r).toBe(true);
  });
});
